### ISSUE TITLE
如何处理 WKWebView 白屏？

### ISSUE THREAD

**Issue by QiuZhiFei** [dequan1331/WKWebViewExtension#1]
如何处理 WKWebView 白屏？

**Comment by dequan1331** [comment]
1.   重新加载Url & 重新加载HTML。
2.  当前页面展示loading页，重新Alloc WebView，重新加载。

有些白屏是crash导致的，有可能不止会影响当前页面，所有活动的WebView最好都需要处理下。

如果像[HybridPageKit](https://github.com/dequan1331/HybridPageKit)使用WebView重用逻辑的话，如果不能准确的处理，最好把回收池里重用的WebView也清理掉。
